language: node_js
before_deploy: npm run build-prod
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  on:
    branch: master
notifications:
  email: false
  slack:
    rooms:
      - rompfgroup:rt1C65fF6zd0w8KMpRo5dM4K#lms-wasm
    on_success: change
    on_failure: always