name: CI

on:
  push:
  schedule:
    # trigger weekly at 12am
    # this build should run with caches disabled
    - cron: "0 0 * * 0"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Setup dependencies
        run: npm ci

      - name: Build and Test Project
        run: npm test
